config/routes.rb
Blogger::Application.routes.draw do
  root to: 'articles#index'

  resources :articles do
  resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

  delete 'articles/remove_image/:id' => "articles#remove_image", as: :remove_image

end

 

app/models/article.rb
class Article < ActiveRecord::Base
	paginates_per 3
	
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	has_attached_file :image, 
		styles: { 
			thumb: "100x100#",
			small: "150x150>",
			medium: "300x300>", 
		 }

	def tag_list
		tags.join(", ")
	end

	def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings

	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	

before_filter :require_login, only: [:new, :create, :edit, :update, :destroy]

	def index
		@articles = Article.order(:title).page(params[:page])
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save

		flash.notice = "'#{@article.title}' is a lovely new article:)"

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id]).destroy
		@article.destroy

		flash.notice = "Are you sure you want to scrap '#{@article.title}' ?"

		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article '#{@article.title}' is much better now!"

		redirect_to article_path(@article)
	end

	def remove_image
		@article = Article.find(params[:id])
		@article.image.destroy
		redirect_to edit_article_path(@article)
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new
  end

  def create
    if login(params[:username], params[:password])
      redirect_back_or_to(articles_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  before_filter :zero_authors_or_authenticated, only: [:new, :create]

  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_filter :require_login, except: [:create]

def create
  @comment = Comment.new(comment_params)
  @comment.article_id = params[:article_id]

  @comment.save

  redirect_to article_path(@comment.article)
end

def comment_params
  params.require(:comment).permit(:author_name, :body)
end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
		include TagsHelper

	before_filter :require_login, only: [:destroy]

	def show
		@tag = Tag.find(params[:id])
	end

	def index
		@tags = Tag.all
	end

	def edit
		@tag = Tag.find(params[:id])
	end

	def update
		@tag = Tag.find(params[:id])
		@tag.update(tag_params)

		flash.notice = "Tag '#{@tag.name}' is much better now!"

		redirect_to tag_path(@tag)
	end

	def destroy
		@tag = Tag.find(params[:id]).destroy
		@tag.destroy

		flash.notice = "Are you sure you want to scrap '#{@tag.name}' ?"

		redirect_to tags_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
	def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/articles/_comment.html.erb
<div>
	<h5><%= comment.author_name %> wrote this comment>></h5>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p><hr />
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:small) %><br/>
    <% end %>
      <%= f.label :image, "Attach/Change Image" %><br />
      <%= f.file_field :image %>
      <% if @article.image.exists? %><hr/>
      <%= link_to "Delete Your Image", remove_image_path(@article), method: :delete %>
      <% end %>
  </p><hr />
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit This Article</h1>

	<%= render partial: 'form' %>

<h6><%= link_to "<<Back to All Articles", articles_path %></h6>

app/views/articles/index.html.erb
<h1>Here There Be Dragons</h1>

<ul id="articles">
	<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
		</li>
	<% end %>
</ul><hr/>

<%=paginate @articles %>

<% if logged_in? %>
	<%= link_to "create more treasures", new_article_path, class: "new_article" %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
	<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
	<p>
		Tags:
		<% @article.tags.each do |tag| %>
			<%= link_to tag.name, tag_path(tag) %>
		<% end %>
	</p>
	<p>
	  <% if @article.image.exists? %>
	  	<%= image_tag @article.image.url(:small) %><br/>
	  <% end %>
	</p>

	<p><%= @article.body %></p>

	<h5><% @article.comments.size %></h5>

		<%= render partial: 'articles/comment', collection: @article.comments %>

		<%= render partial: 'comments/form' %>
		
		<%= link_to "<<Back to Articles List", articles_path %>

	<% if logged_in? %>
		<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "You sure you want to COMPLETELY scrap this?"} %>

		<%= link_to "edit", edit_article_path(@article) %>
	<% end %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to '<<Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Just me</h1>
  <% @authors.each do |author| %>
  
    <h4>Author: <%= author.username %></h4>
        <h4>Email: <%= author.email %></h4><br/>
        <h5><%= link_to 'Show', author %></h5>
        <h5><%= link_to 'Edit', edit_author_path(author) %></h5>
        <h5><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }%></h5>
  <% end %>
<br>

<%= link_to 'Add a New Author>>', new_author_path %><br/>
<%= link_to '<<Back To All Articles', articles_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>What do you think? I <em>may</em> care...</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Who are You?" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "What do you have to say?" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Dragonblog</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	  <p class="flash">
	    <%= flash.notice %>
	  </p>
	  <div id="container">
	    <div id="content">
	      <%= yield %>
	      <hr>
	      <h6>
	        <% if logged_in? %>
	          <%= "Logged in as #{current_user.username}" %>
	          <%= link_to "(logout)", logout_path %>
	        <% else %>
	          <%= link_to "(login)", login_path %>
	        <% end %>
      	</h6>
	    </div>
	  </div>
	</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <ul>
  <% @tag.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
    <% if logged_in? %>
      <p>
        <%= f.label :Tag %><br />
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.submit %>
      </p>
      <p>
        
        	<%= link_to "delete", tag_path, method: :delete, data: {confirm: "You sure you want to COMPLETELY scrap this?"} %>
  </p>
    <% else %>You must be logged in to edit this tag
    <% end %>
    <br/>
  <p>
    <%= link_to "<<Back to Articles List", articles_path %>
  </p>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit This Tag</h1>

	<%= render partial: 'form' %>

app/views/tags/index.html.erb
<h1>Click on a Tag to Edit</h1>

<ul id="tags">
	<% @tags.each do |tag| %>
		<li>
			<%= link_to tag.name, edit_tag_path(tag), class: 'tag_name', id: "tag_#{tag.id}" %>
		</li>
	<% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with '<%= @tag.name %>'</h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<h6>
<%= link_to "<<Back to All Articles", articles_path %></h6><br />
<h6><%= link_to "View All Tags>>", tags_path %></h6>